language: node_js
node_js: node
env:
  # - TYPESCRIPT_VERSION=rc
  - TYPESCRIPT_VERSION=3.9
  # - TYPESCRIPT_VERSION=3.8
  # - TYPESCRIPT_VERSION=3.7
install:
  - npm ci --ignore-scripts
  - npm install typescript@$TYPESCRIPT_VERSION
script: npm run prepare
